# ==================================================================================
from asyncio import AbstractEventLoop
from logging import INFO, Filter, Formatter
from sys import argv
from typing import Any

# ==================================================================================
# GLOBAL default value
# ==================================================================================
EMPTY: str = ""
EMPTYLIST: list = []
EMPTYDICT: dict = {}
EMPTYSET: set = set()
TAB: str = "\t"
LF: str = "\n"

# ==================================================================================
# GLOBAL argument management
# ==================================================================================
def PyCacheClean(directory=".") -> tuple[int, int]: ...
def ProcessArguments(arguments: list[str] = argv) -> tuple[list[str], dict[str, Any]]: ...
def RebuildArguments(app: str = argv[0], *args, **kwargs) -> list[str]: ...

# ==================================================================================
# GLOBAL time shortcuts
# ==================================================================================
def wait(seconds: float) -> None: ...
def asyncWait(seconds: float) -> None: ...

# ==================================================================================
# GLOBAL functions - type check
# ==================================================================================
def isUnion(paramType): ...
def isAny(paramType): ...
def isNone(paramType): ...
def isListOfT(data: list, t: type) -> bool: ...
def Is(provided: Any, expectedType: type) -> bool: ...

# ==================================================================================
# GLOBAL functions - logging
# ==================================================================================
def setupLogging(root: str, defaultLevel=INFO): ...
def setNamespaceLevel(namespace, level): ...
def addFileHandler(name: str, defaultLevel: int, formatter: Formatter, filter: Filter) -> None: ...
def removeFileHandler(name: str) -> None: ...

def verbose(message, *args, **kwargs): ...
def debug(message, *args, **kwargs): ...
def info(message, *args, **kwargs): ...
def warning(message, *args, **kwargs): ...
def error(message, *args, **kwargs): ...
def critical(message, *args, **kwargs): ...
def fatal(message, *args, **kwargs): ...

# ==================================================================================
# GLOBAL functions - string
# ==================================================================================
def StripAnsi(text): ...

# ==================================================================================
# GLOBAL functions - asychronous(asyncio)
# ==================================================================================
def createTask(asyncFunc, *args, **kwargs): ...
def getRunningLoop() -> AbstractEventLoop: ...
def getEventLoop() -> AbstractEventLoop: ...