# ==================================================================================
from typing import Protocol, runtime_checkable


# ==================================================================================
@runtime_checkable
class iENUTSConfiguration[T: iENUTSConfiguration](Protocol): 
    @property
    def LDPath(self): ...
    @property
    def style(self): ...
    @property
    def assetFolder(self): ...
    @property
    def themePath(self): ...

    def save(self, path=None) -> T: ...
    def load(self, path=None) -> T: ...
