# ==================================================================================
from typing import Protocol, overload, runtime_checkable

# ==================================================================================
from ...components import iComponentBase
from .__commandBarButton import iCommandBarButton


# ==================================================================================
@runtime_checkable
class iCommandBarBase(iComponentBase, Protocol):
    @overload
    def addButton(self, button: str) -> iCommandBarButton: ...
    @overload
    def addButton(self, button: iCommandBarButton) -> iCommandBarButton: ...
    def addButton(self, button: str | iCommandBarButton) -> iCommandBarButton: ...

    @overload
    def removeButton(self, button: str): ...
    @overload
    def removeButton(self, button: iCommandBarButton): ...
    def removeButton(self, button: str | iCommandBarButton): ...

    @overload
    def contains(self, button: str) -> bool: ...
    @overload
    def contains(self, button: iCommandBarButton) -> bool: ...    
    def contains(self, button: str |iCommandBarButton) -> bool: ...

    def clear(self) -> None: ...
