# ==================================================================================
# src/jAGFx/types/interface/configuration/__applicationConfiguration.py
# ==================================================================================
from typing import Protocol, runtime_checkable

# ==================================================================================
from .__configuration import iConfiguration


# ==================================================================================
@runtime_checkable
class iApplicationConfiguration(Protocol):
    def __init__(self, Title: str = "", Company: str = "", ApplicationId: str = "", Icon: str = "") -> None: ...
    @property
    def sections(self) -> dict[str, iConfiguration]: ...
    @property
    def updatedAttributes(self) -> set: ...
    @property
    def isDirty(self) -> bool: ...
    @property
    def style(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def company(self) -> str: ...
    @property
    def applicationId(self) -> str: ...
    @property
    def icon(self) -> str: ...
    def load(self, path: str = None) -> iConfiguration: ...
    def save(self, path: str = None) -> None: ...
